services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OIDO_BINARY: ./oido
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    image: oido-std:latest
    container_name: oido-std
    restart: unless-stopped
    ports:
      - 5417:3000
    environment:
      - AGENT_WORKDIR=/home/node
    volumes:
      - ./data:/app/data
      - /usr/local/bin/oido:/usr/local/bin/oido
      - /home/djan/.config/oido:/home/node/.config/oido:rw
      - /home/djan/.cache/oido:/home/node/.cache/oido:rw
      - /home/djan/.local/share/oido:/home/node/.local/share/oido:rw
      - /home/djan/.ssh:/home/node/.ssh:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oido.rule=Host(`oido.bruna-tech.com`)"
      - "traefik.http.routers.oido.entrypoints=websecure"
      - "traefik.http.routers.oido.tls.certResolver=myresolver"
      - "traefik.http.services.oido.loadbalancer.server.port=3000"
      - "traefik.http.routers.oido.priority=1"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
